language: node_js
addons:
  code_climate:
    repo_token: 7c0e198cf2d230db0a116f47682214f47d25b0208a8c645f793665ac905926dc 
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive --require ./test/setup.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - rm -rf ./coverage
